### ISSUE TITLE
 UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by tekwreck** [slayerinc/AntiSwear-Bot#1]
Running code as is, tried to .add no errors but when I .list i get this error
```
(node:33688) UnhandledPromiseRejectionWarning: TypeError: get.map is not a function
    at F:\AntiSwear-Bot-master\commands\list.ts:19:13
    at step (F:\AntiSwear-Bot-master\commands\list.ts:33:23)
    at Object.next (F:\AntiSwear-Bot-master\commands\list.ts:14:53)
    at fulfilled (F:\AntiSwear-Bot-master\commands\list.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:33688) UnhandledPromiseRejectionWarning: TypeError: get.map is not a function
    at F:\AntiSwear-Bot-master\commands\list.ts:19:13
    at step (F:\AntiSwear-Bot-master\commands\list.ts:33:23)
    at Object.next (F:\AntiSwear-Bot-master\commands\list.ts:14:53)
    at fulfilled (F:\AntiSwear-Bot-master\commands\list.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:33688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:33688) UnhandledPromiseRejectionWarning: TypeError: get.map is not a function
    at F:\AntiSwear-Bot-master\commands\list.ts:19:13
    at step (F:\AntiSwear-Bot-master\commands\list.ts:33:23)
    at Object.next (F:\AntiSwear-Bot-master\commands\list.ts:14:53)
    at fulfilled (F:\AntiSwear-Bot-master\commands\list.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by tekwreck** [comment]
I installed the lastest NPM LTS for this if that helps.
